강원대 Android_권새일 3주차 과제 Step2
kakao-tech-campus-2nd-step2/android-map-search pull request #102
Opened 2024-07-12 06:57 UTC by todlf

**어려웠던 점**
- kakaoMap 설정이 복잡해서 좀 시간이 걸렸습니다.
- 처음에 openSSL을 이용해 해시 키 값을 찾았으나 인증 오류가 떠서, kakaoSDK를 통해 해시 키 값을 찾으니 다르게 나와서 적용시키니 해결되었습니다. 왜 openSSL로 찾은 해시 키 값이 다를까요?
- MVVM 적용에서 저번 피드백 받은 saveDb()와 loadDb()만 일단 옮겨놓았는데 다른 부분은 아직 시도중입니다...😓
-
**중점적으로 리뷰해주셨으면 하는 부분**
- MVVM 패턴이나 다른 작성된 코드의 개선할 점 알려주시면 좋겠습니다!

2024-07-13 15:27 UTC, kold-brewed commented
@todlf step1을 머지하면서 step2 PR에도 충돌이 생겼네요 🥲 동일하게 Resolve conflicts 버튼으로 최종 제출하셨던 형태와 동일하게 수정 부탁드리겠습니다.

2024-07-14 01:36 UTC, todlf commented
@kold-brewed 수정했습니다

2024-07-14 06:13 UTC, kold-brewed requested changes
2단계 과제도 잘 진행해주셨네요! 다만, 1단계 과제 피드백을 반영하시는 과정에서 검색 기능이 제대로 동작하고 있지 않습니다. 이 부분 먼저 수정해주시고, 이후에 피드백 남긴 부분들도 확인 부탁드립니다.

2024-07-14 06:13 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/KakaoMapView.kt
> +        KakaoMapSdk.init(this, key)
지도 SDK는 Activity의 onCreate()에서 초기화 하는 방법도 있지만, Application 클래스를 이용해 초기화 해주는 방법도 있습니다.

Application 클래스는 다른 Activity나 컴포넌트들보다도 앞서서 실행됩니다. 지금처럼 SDK를 통해 화면을 그려야 하고, 그 화면이 앱사용을 위한 필수적인 요소일 때에 Application 클래스에서 SDK를 초기화 해주면 KakaoMapView Activity에 진입했을 때 조금 더 빠르게 지도 화면을 구성해줄 수 있어요. 반면에 특정 화면에서만 사용되고, 유저가 그 화면을 이용하는 경우가 드문 경우에 Application 클래스에 정의하게 되면 오히려 앱 초기 속도를 느리게 만들게 될 수도 있습니다. 

```kotlin
class ApplicationClass : Application() {
	...
	override fun onCreate() {
		super.onCreate()
		KakaoMapSdk.init(this, "네이티브 앱 키")
		...
	}
	...
}
```

앞으로 프로젝트에서 SDK를 사용하게 되실 경우에는 이런 점을 고려해서 초기화 시점을 정해주시면 좋을 것 같아요!

2024-07-14 06:59 UTC, kold-brewed commented
> 왜 openSSL로 찾은 해시 키 값이 다를까요?

@todlf 
음.. OpenSSL로 찾으실 때 시도하신 명령어를 남겨주시면 좀 더 확인해볼 수 있을 것 같아요.
보통 프로젝트를 열면 debug로 세팅이 되어있어서 `Utility.getKeyHash(this)`로 구하시면 디버그 키해시를 가져올텐데요. OpenSSL 통해서 가져오실 때 keytool 명령어 -storepass나 -keypass 같은 파라미터나 다른 설정값들이 달라서 결과도 다르게 나온게 아닐까 싶네요.

2024-07-14 09:15 UTC, todlf commented
OpenSSL로 찾을 때 `keytool -exportcert -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64` 이 명령어로 해서 키해시를 갖고 와서 플랫폼 등록을 하니 401 인증오류가 났습니다... kakaoSDK로 갖고 온 키해시는 잘 동작했습니다

2024-07-14 12:11 UTC, kold-brewed commented
> OpenSSL로 찾을 때 `keytool -exportcert -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore -storepass android -keypass android | openssl sha1 -binary | openssl base64` 이 명령어로 해서 키해시를 갖고 와서 플랫폼 등록을 하니 401 인증오류가 났습니다... kakaoSDK로 갖고 온 키해시는 잘 동작했습니다

다른 파라미터들은 다 괜찮아보이는 걸로 봐선 -keystore 파라미터가 제일 의심스럽네요 🤨
`%USERPROFILE%\.android\debug.keystore`
%USERPROFILE% 요 환경변수가 잘 정의되어있는지, 윈도우 터미널에서 위 경로로 접근했을 때 debug.keystore 파일이 잘 있는지도 확인해주시면 좋을 것 같아요.

2024-07-14 12:13 UTC, merged

2024-07-14 12:27 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/SearchDbHelper.kt
> +                ).awaitResponse()
@todlf 
지난번에 정의하신 enqueue와는 다르게 awaitResponse()는 불친절하게도 네트워크 오류상황일 때 예외를 밖으로 던집니다. 비행기모드를 켠 뒤에 검색어 입력창을 클릭해보시면 앱이 죽을거예요. 서버 요청을 구현하실 때에는 Retrofit 라이브러리에서 예외를 어떻게 처리하는지를 파악하고 필요하면 try-catch 혹은 runCatching으로 감싸주셔야 합니다.