강원대_Android_이아림_3주차과제_STEP2
kakao-tech-campus-2nd-step2/android-map-search pull request #74
Opened 2024-07-11 07:23 UTC by arieum

아직 STEP0, STEP1 피드백을 못받았지만...! 슬쩍 STEP2 PR도 보내봅니다

- 윈도우 기반에서 지도API 가져오는 과정이 너무 험악했습니다.. 이번 프로젝트 재밌지만.. 호락호락하진 않은 느낌입니다..!!  
- ListAdapter로 상속받는 거 이제야 구현해봤는데 왜 이걸 이제야 했는가..! 싶을 정도로 RecyclerviewAdapter보다 좋았습니다..!  notify()보다 더 좋은 submitlist() 메서드가 있다니..! 😮 검색결과Recyclerview는 LIstAdapter 상속으로 바꾸고 notify()를 submitlist로 바꾸는데 수월했지만 검색기록TabRecyclerview는 스파게티코드가 많이 섞여있어 섣불리 못바꾸었습니다..!!

2024-07-12 09:40 UTC, mkSpace requested changes

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/KakaoResponse.kt
> +    val same_name: Any?,
Kotlin Convention은 CamelCase인데 여기에 SnakeCase로 작성되었네요?
혹시 응답 json의 형태가 snakeCase여서 그런거면 `@SerializedName` 을 사용해보세요!

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        placeList = placeRepository.insertInitialData()
아직 Repository들을 View에서 직접 세팅하고 사용하고 계신데 ViewModel로 옮기셔야 합니다

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        textWatcher?.let { input.removeTextChangedListener(it) }
리뷰 사항 적용하셨네요 👍

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        }
```suggestion
        tabRecyclerView.isVisible = placeRepository.hasResearchEntries()
```
로 더 깔끔하게 바꿀 수 있겠네요

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        resultAdapter.submitList(placeList)
ViewModel을 적용하기가 조금 어렵다고 하셨는데 이번주까지만 MVC로 진행하시고 이번에 Step3 작업 하신 이후에는 조금씩이나마 ViewModel을 사용해서 데이터 흐름이 LocalDB -> View로 오는 흐름을 만들어보세요
실무에서는 다 이런 방식으로 설계하기 때문에 결국 부딪혀야 합니다. 강사님과 멘토 믿고 부족해도 괜찮으니 시도해보세요!

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/Place.kt
> +data class Place (
Place가 DB에 저장되고 있으며 INTEGER id를 PK로 갖고 있는데 여기에는 id가 없는 이유가 있을까요?

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/PlaceDiffCallback.kt
> +        return oldItem.name == newItem.name
Place의 name은 충분히 중복이 될 수 있다고 생각이 드네요. Plcae의 id아 Primary Key로 사용되고 unique 하니 그걸 아이템이 같은지 비교할 때 사용하는게 더 나을것 같습니다.

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/PlaceRepository.kt
> +        try {
db나 cursor는 Closeable Interface이기 떄문에 use 확장함수를 지원합니다. use 확장함수를 사용하면 내부에서 알아서 예외처리는 물론 close 까지 수행해주기에 개발할 때 필요한 로직만 작성할 수 있다는 장점이 있습니다. use 한번 확인해보세요!

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/PlaceRepository.kt
> +                    count!! > 0
cusor.getIntOrNull 하시고 !!를 사용하신거면 그냥 cursor.getInt() 하신거랑 별반 차이가 없습니다. null-safe를 지원하는 함수를 썼으니 (cursor.getIntOrNull(0) ?: 0) > 0 식으로 변경해서 null-safe 하게 프로그래밍 하시는걸 추천드립니다

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/PlaceRepository.kt
> +            .create(KakaoApiService::class.java)
조금 챌린지일 수 있는데 매번 카카오 통신을 할 때 Retrofit을 통해 Client를 항상 생성해서 KakaoApiService를 생성해줘야 할지 잘 생각해보세요.
어떤 방식으로 리팩토링 하면 좋을지 생각해보시고 의견 남겨주세요

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/TextViewExtension.kt
> +public inline fun TextView.addTextChangedListener(
엥 요걸 직접 추가하신거에요? 이거 기본으로 제공하고 있어요
![image](https://github.com/user-attachments/assets/e52d18db-8dab-4444-9dc0-cb8aebe67467)

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintRight_toRightOf="parent" />
Left -> Start
Right -> End
로 변경해주시고 통일해주세요

2024-07-12 09:40 UTC, mkSpace commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintRight_toRightOf="parent" />
ConstraintLayout에서 match_parent를 적용하는 정석적인 방법은 leftOfLeft = parent, rightOfRight=parent로 한 후 width = 0으로 설정하는거에요.

2024-07-12 09:50 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/TextViewExtension.kt
> +public inline fun TextView.addTextChangedListener(
🫢🫢🫢

2024-07-12 10:36 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/KakaoResponse.kt
> +    val same_name: Any?,
🫢Retrofit에서 데이터 클래스를 설정할 때 응답 변수명이랑 데이터 클래스 필드 변수명이 동일해야하는 줄 알았습니다..🫢

2024-07-12 11:39 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/PlaceDiffCallback.kt
> +        return oldItem.name == newItem.name
저번주과제 피드백을 반영해서 이번에는 **RecyclerViewAdapter**를 `RecyclerView.Adapter` 대신` ListAdapter`를 상속받아 구현했습니다!😀 그래서 이 클래스가 사실 필요 없어졌는데 삭제하는 걸 깜빡한 것 같습니다😅 
이 클래스를 삭제하고, RecyclerViewAdapter의 내부 클래스에서 id 비교를 통해 변경 사항을 처리하도록 수정했습니다!

2024-07-12 15:00 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/PlaceRepository.kt
> +            .create(KakaoApiService::class.java)
흠.. 🤔 이부분에 대해서 챗지피티 도움없이 고민하고 있습니다. 처음에는 "아 이거 너무 하드코딩이니까 콜백메서드로 감싸는 걸 의미하시는 걸까" 했지만 이것도 어차피 매번 client를 생성하는 거니까 아닌 것 같고.. 해답을 찾으려면 이 코드를 좀 더 분석해봐야할 것 같습니다. 이 코드가 어떻게 client를 생성하는지, 어떻게 request를 날리는지 좀더 알아보고 답변하겠습니다!!

2024-07-12 15:30 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/PlaceRepository.kt
> +            .create(KakaoApiService::class.java)
처음에는 `콜백메서드`를 권장하시는 걸까 했는데 이것도 결국은 매번 Client를 생성하는 구조였습니다.
그래서 `object`를 사용해서 retrofit 객체를 싱글톤으로 생성했습니다! retrofit 객체는 어차피 읽기전용이라 `by lazy`(학습일지 코치님이 최근에 전달해주신 팁을 적용해봤습니다..!ㅎ)를 사용했습니다!
다만 이걸 고민하면서 든 생각은 제가 코드를 외우듯이 써서 실제로 이 코드가 어떻게 network request를 날리는지에  대한 구조를 완전히 간과하고 있었다는 걸 깨달았습니다. 그래서 더 깊게 파보는 중입니다🤔

2024-07-14 14:56 UTC, mkSpace approved these changes

2024-07-14 15:17 UTC, mkSpace commented
아림님 키워드 검색 부분이 구현되지 않은것 같은데 맞나요??

2025-09-19 08:28 UTC, closed without merging