부산대 Android_김주송_3주차 과제 (STEP2)
kakao-tech-campus-2nd-step2/android-map-search pull request #95
Opened 2024-07-12 06:05 UTC by jooiss

## 파일 구조 설명
**- Place 데이터**
  - `PlaceDataModel` : Place 데이터 클래스
  - `PlaceContract` : 데이터베이스 스키마와 관련된 정보 포함
  - `PlaceDatabaseHelper` : SQLite 데이터베이스 CRUD 작업
  
**- RecyclerView 어댑터**
  - `PlaceRecyclerViewAdapter` : Place 목록 RecyclerView 관련 어댑터
  - `SearchRecyclerViewAdapter` : Search 저장 목록 RecyclerView 관련 어댑터
  
**- 카카오 로컬 API**
  - `KakaoLocalDTO` : 카카오 로컬 API 관련 Data Transfer Object
  - `CategoryGroupCodes` : 카테고리 그룹과 검색어를 mapping하기 위한 Object
  - `RetrofitLocalService` : Retrofit interface
  
**- 카카오 지도 API**
  - `KakaoMapApplication` : 카카오 지도 API 네이티브 앱 키 추가
  
**- Activity**
  - `MapActivity` : 지도 관련 Activity
  - `PlaceActivity` : 검색 관련 Activity

## 코드 작성 시, 어려웠던 점
- 2주차 과제를 제대로 이해한 후에 리팩토링하여 다시 진행하여 시간이 오래 소요됐습니다.
- MVVM 패턴을 고려하여 만들고자 했으나 어떻게 분리를 해야할 지 잘 감이 오지 않아 어려웠습니다.
- 종속성을 제거하기 위해 코드를 역할에 맞게 분리하고 싶었지만, 제대로 진행되지 않아서 조금 더 확인 후, 리팩토링할 예정입니다.

## 중점적으로 리뷰해주셨으면 하는 부분
- MVVM 패턴을 고려해 파일을 분리하기 위해서 어떤 식으로 분리해야 할 지 고민입니다.
- 데이터 부분과 데이터 접근하는 부분, 비즈니스 로직 부분을 나눠 작성하였는데 제가 작성한 부분이 맞는지, 분리한다면 어떤 것을 따로 빼는 것이 좋을 지에 대해 알고 싶습니다.

## 실행 영상
[assignment3_jooiss.webm](https://github.com/user-attachments/assets/d3fb1708-debd-4ce1-8ecb-e89992d2cfb7)

---

바쁘신 와중에 항상 피드백 해주셔서 감사합니다. 좋은 하루 되세요 😄

2024-07-14 14:50 UTC, LeeOhHyung requested changes
@jooiss 3주차 과제 고생많으셨습니다! 코멘트 확인한번 부탁드립니다.

2024-07-14 14:50 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/KakaoLocalDTO.kt
> +)
만약 API response로 내려오는 이름과 다른것을 사용하고 싶다면, [Gson - SerializedName](https://onlyfor-me-blog.tistory.com/923) 어노테이션을 붙여주는 방법도 있습니다. 그래서 꼭 snake_case를 사용하지 않아도 됩니다!

2024-07-14 14:50 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/MapActivity.kt
> +        }
mapView의 resume, pause는 Activity Lifecycle 생명주기 상의 onResume, onPause 에서 호출하는것이 맞는것 같습니다. `MapLifeCycleCallback` 에 넣으면 mapView.resume()이 호출될때 실행되는 콜백들을 의미할겁니다. 따라서 resume, pause, start, finish 4가지 메소드에 대해서 액티비티 생명주기 상에서 실행되도록 수정할 필요가 있을것 같습니다. 

(참고) https://apis.map.kakao.com/android_v2/docs/getting-started/precautions/#1-지도-api-의-라이프사이클

2024-07-14 14:50 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/PlaceActivity.kt
> +        })
MVVM을 지키는 방법중에 하나로 데이터를 조회하는 부분을 View Layer에서 분리시키는것이 있습니다. 
화면 입장에서는 검색결과를 어디에서 가지고 오는지는 관심사가 아니고, 검색결과 데이터가 화면에 까지 전달되는지만 보면 되기 때문입니다. 그래서, network api 통신 하는 코드들은 activity와 별도로 분리하신다면 조금더 깔끔해질것 같습니다.

2024-07-14 14:50 UTC, LeeOhHyung commented on app/src/main/res/layout/map_layout.xml
> +        app:layout_constraintVertical_bias="0.0" />
`layout_constraintHorizontal_bias`, `layout_constraintVertical_bias` 는 없어도 될것 같습니다!

2024-07-14 15:08 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/KakaoLocalDTO.kt
> +)
안 그래도 경고 알림 때문에 변경하고 싶었는데 감사합니다!

2024-07-14 15:22 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/MapActivity.kt
> +        }
제가 잠깐 착각을 했던 것 같습니다. 수정 후 다시 업로드했습니다. 참고자료까지 감사합니다!

2024-07-14 15:22 UTC, jooiss commented on app/src/main/res/layout/map_layout.xml
> +        app:layout_constraintVertical_bias="0.0" />
디자인 칸에서 만지다가 자동으로 들어간 것 같습니다. 세심한 피드백 감사합니다!

2024-07-14 15:47 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/CategoryGroupCodes.kt
> +    }
CategoryGroup을 앱에서 가지고 있도록 구현하셨군요
find 를 사용하게 되면 매번 리스트를 순회하게 될것이므로, map 자료구조를 사용해서 카테고리 정보를 가지고 있는것도 방법일것 같습니다. key-value에서 key를 한글이름으로 하면 될것 같네요

2024-07-15 08:12 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/PlaceActivity.kt
> +        })
Retrofit 객체(RetrofitInstance)와 그것을 이용해 데이터 조회하는 부분(PlaceRepository)을 분리해보았습니다.

2024-07-15 08:13 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/CategoryGroupCodes.kt
> +    }
훨씬 효율적인 코드인 것 같습니다. map을 사용하는 방법 기억하겠습니다!

2024-07-15 15:03 UTC, LeeOhHyung approved these changes
LGTM~! @jooiss 고생많으셨습니다

2024-07-15 15:04 UTC, merged